spring:
  application:
    name: hot-place-research
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${RDB_HOST:localhost}:${RDB_PORT:3306}/${RDB_SCHEMA:hot_place_research}?useSSL=false
    username: ${RDB_USER:root}
    password: ${RDB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${RDB_DDL-AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
